name: AnnikA-B
favicon: null
layout_spectrum: 0.73058
typography_spectrum: 0.99613
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#030303'
    - '#d2bca5'
    - '#595959'
    - '#03a79d'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
